backend:
  name: github
  branch: master
  repo: fysiotherapiedouma/FDwebsite
  site_domain: fysiodouma.netlify.app

publish_mode: editorial_workflow

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

site_url: https://www.fysiodouma.nl
display_url: https://www.fysiodouma.nl

collections:
  - name: "specialisaties"
    label: "Specialisaties"
    folder: "content/dutch/specialisatie"
    nested:
      depth: 100
      summary: '{{title}}'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "locaties"
    label: "Locaties"
    folder: "content/dutch/locatie"
    nested:
      depth: 100
      summary: '{{title}}'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "medewerkers"
    label: "Medewerkers"
    folder: "content/dutch/medewerker"
    nested:
      depth: 100
      summary: '{{title}}'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro", name: "intro", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "samenwerkingen"
    label: "Samenwerkingen"
    folder: "content/dutch/samenwerkingen"
    nested:
      depth: 100
      summary: '{{title}}'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Overige pagina's"
    folder: "content/dutch/page"
    nested:
      depth: 100
      summary: '{{title}}'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "special"
    label: "Speciale pagina's"
    files:
      - name: "home"
        label: "Homepagina"
        file: content/dutch/_index.md
        fields: # The fields for each document, usually in front matter
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Body", name: "body", widget: "markdown"}
